/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleAnchor } from "./SimpleAnchor";
export * as factories from "./factories";
export { SimpleAnchor__factory } from "./factories/SimpleAnchor__factory";
