/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SimpleAnchorInterface extends Interface {
  getFunction(nameOrSignature: "anchor" | "operator"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MerkleRootAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchor",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;

  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
}

export namespace MerkleRootAnchoredEvent {
  export type InputTuple = [
    merkleRoot: BytesLike,
    timestamp: BigNumberish,
    batchId: string
  ];
  export type OutputTuple = [
    merkleRoot: string,
    timestamp: bigint,
    batchId: string
  ];
  export interface OutputObject {
    merkleRoot: string;
    timestamp: bigint;
    batchId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleAnchor;
  waitForDeployment(): Promise<this>;

  interface: SimpleAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchor: TypedContractMethod<
    [merkleRoot: BytesLike, batchId: string],
    [void],
    "nonpayable"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [merkleRoot: BytesLike, batchId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MerkleRootAnchored"
  ): TypedContractEvent<
    MerkleRootAnchoredEvent.InputTuple,
    MerkleRootAnchoredEvent.OutputTuple,
    MerkleRootAnchoredEvent.OutputObject
  >;

  filters: {
    "MerkleRootAnchored(bytes32,uint256,string)": TypedContractEvent<
      MerkleRootAnchoredEvent.InputTuple,
      MerkleRootAnchoredEvent.OutputTuple,
      MerkleRootAnchoredEvent.OutputObject
    >;
    MerkleRootAnchored: TypedContractEvent<
      MerkleRootAnchoredEvent.InputTuple,
      MerkleRootAnchoredEvent.OutputTuple,
      MerkleRootAnchoredEvent.OutputObject
    >;
  };
}
