import { Permission } from '@biffco/core/rbac'

export interface ActorTypeDefinition {
  id: string
  name: string
  permissions: Permission[]
}

export const livestockActorTypes: ActorTypeDefinition[] = [
  {
    id: 'BovineProducer',
    name: 'Productor Ganadero',
    permissions: [
      Permission.ASSETS_CREATE,
      Permission.ASSETS_READ,
      Permission.ASSETS_UPDATE,
      Permission.ASSETS_SPLIT,
      Permission.ASSETS_MERGE,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.TRANSFERS_INITIATE,
      Permission.TRANSFERS_ACCEPT,
      Permission.TRANSFERS_REJECT,
      Permission.HOLDS_IMPOSE,
      Permission.HOLDS_LIFT,
      Permission.FACILITIES_MANAGE,
      Permission.ZONES_MANAGE,
      Permission.PENS_MANAGE,
      Permission.ORG_MANAGE,
      Permission.MEMBERS_INVITE,
      Permission.MEMBERS_REVOKE,
      Permission.EMPLOYEES_MANAGE,
      Permission.BILLING_MANAGE,
      Permission.SETTINGS_MANAGE,
      Permission.CERTIFICATIONS_LINK,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'Veterinarian',
    name: 'Veterinario de Campo',
    permissions: [
      Permission.ASSETS_READ,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.HOLDS_IMPOSE,
      Permission.HOLDS_LIFT,
      Permission.CERTIFICATIONS_LINK,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'SenasaInspector',
    name: 'Inspector SENASA',
    permissions: [
      Permission.ASSETS_READ,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.HOLDS_IMPOSE,
      Permission.HOLDS_LIFT,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'LivestockCarrier',
    name: 'Transportista',
    permissions: [
      Permission.ASSETS_READ,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'FeedlotOperator',
    name: 'Feedlot / Engordador',
    permissions: [
      Permission.ASSETS_CREATE,
      Permission.ASSETS_READ,
      Permission.ASSETS_UPDATE,
      Permission.ASSETS_SPLIT,
      Permission.ASSETS_MERGE,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.TRANSFERS_INITIATE,
      Permission.TRANSFERS_ACCEPT,
      Permission.TRANSFERS_REJECT,
      Permission.FACILITIES_MANAGE,
      Permission.ZONES_MANAGE,
      Permission.PENS_MANAGE,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'SlaughterhouseOperator',
    name: 'Frigorífico',
    permissions: [
      Permission.ASSETS_READ,
      Permission.ASSETS_UPDATE,
      Permission.ASSETS_SPLIT,
      Permission.ASSETS_MERGE,
      Permission.ASSETS_TRANSFORM, // Crítico para faena atómica
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.TRANSFERS_INITIATE,
      Permission.TRANSFERS_ACCEPT,
      Permission.TRANSFERS_REJECT,
      Permission.FACILITIES_MANAGE,
      Permission.ZONES_MANAGE,
      Permission.PENS_MANAGE,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'AccreditedLaboratory',
    name: 'Laboratorio Acreditado',
    permissions: [
      Permission.ASSETS_READ,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.CERTIFICATIONS_LINK,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'Exporter',
    name: 'Exportador',
    permissions: [
      Permission.ASSETS_READ,
      Permission.ASSETS_SPLIT,
      Permission.ASSETS_MERGE,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.TRANSFERS_INITIATE,
      Permission.TRANSFERS_ACCEPT,
      Permission.TRANSFERS_REJECT,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'EUImporter',
    name: 'Importador / Distribuidor UE',
    permissions: [
      Permission.ASSETS_READ,
      Permission.ASSETS_SPLIT,
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.TRANSFERS_INITIATE,
      Permission.TRANSFERS_ACCEPT,
      Permission.TRANSFERS_REJECT,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'RetailerProcessor',
    name: 'Minorista / Procesador en destino',
    permissions: [
      Permission.ASSETS_READ,
      Permission.ASSETS_SPLIT, // Permite subdividir medial res a cortes menores
      Permission.EVENTS_APPEND,
      Permission.EVENTS_READ,
      Permission.TRANSFERS_INITIATE,
      Permission.TRANSFERS_ACCEPT,
      Permission.TRANSFERS_REJECT,
      Permission.ANALYTICS_VIEW,
    ],
  },
  {
    id: 'ExternalAuditor',
    name: 'Auditor Externo',
    permissions: [
      Permission.ASSETS_READ,
      Permission.EVENTS_READ,
      Permission.ANALYTICS_VIEW,
      Permission.REPORTS_GENERATE,
      Permission.AUDIT_READ,
    ],
  },
]
