export const Permission = {
  ASSETS_CREATE:     "assets.create",
  ASSETS_READ:       "assets.read",
  ASSETS_UPDATE:     "assets.update",
  ASSETS_SPLIT:      "assets.split",
  ASSETS_MERGE:      "assets.merge",
  ASSETS_TRANSFORM:  "assets.transform",
  EVENTS_APPEND:     "events.append",
  EVENTS_READ:       "events.read",
  TRANSFERS_INITIATE:  "transfers.initiate",
  TRANSFERS_ACCEPT:    "transfers.accept",
  TRANSFERS_REJECT:    "transfers.reject",
  HOLDS_IMPOSE:      "holds.impose",
  HOLDS_LIFT:        "holds.lift",
  FACILITIES_MANAGE: "facilities.manage",
  ZONES_MANAGE:      "zones.manage",
  PENS_MANAGE:       "pens.manage",
  ORG_MANAGE:        "org.manage",
  MEMBERS_INVITE:    "members.invite",
  MEMBERS_REVOKE:    "members.revoke",
  EMPLOYEES_MANAGE:  "employees.manage",
  BILLING_MANAGE:    "billing.manage",
  SETTINGS_MANAGE:   "settings.manage",
  CERTIFICATIONS_LINK: "certifications.link",
  ANALYTICS_VIEW:    "analytics.view",
  REPORTS_GENERATE:  "reports.generate",
  AUDIT_READ:        "audit.read",
} as const

export type Permission = typeof Permission[keyof typeof Permission]
